/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Thu May 4 18:26:02 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <qfont.h>
#include <kquickhelp.h>
#include <qpixmap.h>
#include "decrypt.h"
#include "common.h"

void  decrypt::initDialog(){
  this->resize(400,330);
  this->setMinimumSize(400,330);
  this->setMaximumSize(400,330);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(50,10,340,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setFont(QFont("helvetica", 20, 50));
  QLabel_1->setText(i18n("KWoodhammer Decryption"));

  QPushButton_1= new QPushButton(this,"NoName");
  QPushButton_1->setGeometry(10,290,100,30);
  QPushButton_1->setMinimumSize(0,0);
  QPushButton_1->setText(i18n("OK"));

  QGroupBox_1= new QGroupBox(this,"NoName");
  QGroupBox_1->setGeometry(10,80,380,80);
  QGroupBox_1->setMinimumSize(0,0);

  QLabel_3= new QLabel(QGroupBox_1,"NoName");
  QLabel_3->setGeometry(10,10,80,20);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Key length:"));

  QSlider_1= new QSlider(QGroupBox_1,"NoName");
  QSlider_1->setGeometry(100,10,70,20);
  QSlider_1->setMinimumSize(0,0);
  QSlider_1->setValue(5);
  QSlider_1->setRange(1,99);
  QSlider_1->setOrientation(QSlider::Horizontal);

  QLineEdit_1= new QLineEdit(QGroupBox_1,"NoName");
  QLineEdit_1->setGeometry(180,10,60,20);
  QLineEdit_1->setMinimumSize(0,0);
  QLineEdit_1->setText(i18n("5"));

  QPushButton_3= new QPushButton(QGroupBox_1,"NoName");
  QPushButton_3->setGeometry(250,50,120,20);
  QPushButton_3->setMinimumSize(0,0);
  KQuickHelp::add(QPushButton_3,i18n("<blue>Trial<br><black>Searches for occurrences of periodic repetitions<br>and makes suggestions about the key length.<br>Trial length determines the level of detail of the search.<br><red>Kasiski, Friedrich W.<br><black>A Prussian officer who invented the algorithm<br>to find out the length of the key in a polyalphabetical<br>encrypted message, using the difference of two<br>same words or word groups."));
  QPushButton_3->setText(i18n("Trial (Kasiski)"));

  QPushButton_4= new QPushButton(QGroupBox_1,"NoName");
  QPushButton_4->setGeometry(250,10,120,20);
  QPushButton_4->setMinimumSize(0,0);
  KQuickHelp::add(QPushButton_4,i18n("<blue>Statistics Table<br><black>Presents a table according to the key length.<br>Using the table you can decrypt anything step by step."));
  QPushButton_4->setText(i18n("Statistic Table"));

  QLabel_4= new QLabel(QGroupBox_1,"NoName");
  QLabel_4->setGeometry(10,50,80,20);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Trial length:"));

  QSlider_2= new QSlider(QGroupBox_1,"NoName");
  QSlider_2->setGeometry(100,50,70,20);
  QSlider_2->setMinimumSize(0,0);
  QSlider_2->setValue(5);
  QSlider_2->setRange(2,15);
  QSlider_2->setOrientation(QSlider::Horizontal);

  QLineEdit_2= new QLineEdit(QGroupBox_1,"NoName");
  QLineEdit_2->setGeometry(180,50,60,20);
  QLineEdit_2->setMinimumSize(0,0);
  QLineEdit_2->setText(i18n("5"));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,50,100,20);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Code details"));

  QGroupBox_2= new QGroupBox(this,"NoName");
  QGroupBox_2->setGeometry(10,10,30,30);
  QGroupBox_2->setMinimumSize(0,0);
  QGroupBox_2->setBackgroundPixmap(QPixmap(iniconhome("kwoodencrypt.xpm")));

  QMultiLineEdit_1= new QMultiLineEdit(this,"NoName");
  QMultiLineEdit_1->setGeometry(350,260,40,30);
  QMultiLineEdit_1->setMinimumSize(0,0);
  QMultiLineEdit_1->hide();

  QGroupBox_3= new QGroupBox(this,"NoName");
  QGroupBox_3->setGeometry(10,200,380,80);
  QGroupBox_3->setMinimumSize(0,0);
  QGroupBox_3->show();
  QGroupBox_3->setEnabled(false);

  QLabel_6= new QLabel(QGroupBox_3,"NoName");
  QLabel_6->setGeometry(10,10,70,20);
  QLabel_6->setMinimumSize(0,0);
  QLabel_6->setText(i18n("Char 1"));

  QSlider_3= new QSlider(QGroupBox_3,"NoName");
  QSlider_3->setGeometry(90,10,90,20);
  QSlider_3->setMinimumSize(0,0);
  QSlider_3->setRange(1,99);
  QSlider_3->setOrientation(QSlider::Horizontal);

  QLabel_7= new QLabel(QGroupBox_3,"NoName");
  QLabel_7->setGeometry(190,10,180,20);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("(with key letter: 1)"));

  QLabel_10= new QLabel(QGroupBox_3,"NoName");
  QLabel_10->setGeometry(90,40,90,20);
  QLabel_10->setMinimumSize(0,0);
  QLabel_10->setText(i18n("Label"));

  QComboBox_2= new QComboBox(QGroupBox_3,"NoName");
  QComboBox_2->setGeometry(280,40,90,20);
  QComboBox_2->setMinimumSize(0,0);

  QLabel_8= new QLabel(QGroupBox_3,"NoName");
  QLabel_8->setGeometry(10,40,70,20);
  QLabel_8->setMinimumSize(0,0);
  QLabel_8->setText(i18n("Code"));

  QLabel_9= new QLabel(QGroupBox_3,"NoName");
  QLabel_9->setGeometry(190,40,80,20);
  QLabel_9->setMinimumSize(0,0);
  QLabel_9->setText(i18n("Cleartext"));

  QLabel_5= new QLabel(this,"NoName");
  QLabel_5->setGeometry(10,170,100,20);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n("Table"));

  QPushButton_5= new QPushButton(this,"NoName");
  QPushButton_5->setGeometry(120,290,100,30);
  QPushButton_5->setMinimumSize(0,0);
  QPushButton_5->setText(i18n("Switch View"));

}
