/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 30 19:39:56 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <kiconloader.h>
#include <qfont.h>
#include <kquickhelp.h>
#include <qpixmap.h>
#include "encrypt.h"
#include "common.h"

void  encrypt::initDialog(){
  KIconLoader loader;

  this->resize(400,290);
  this->setMinimumSize(400,290);
  this->setMaximumSize(400,290);
  QPushButton_1= new QPushButton(this,"NoName");
  QPushButton_1->setGeometry(10,250,100,30);
  QPushButton_1->setMinimumSize(0,0);
  QPushButton_1->setEnabled(false);
  QPushButton_1->setText(i18n("Encrypt"));

  QPushButton_2= new QPushButton(this,"NoName");
  QPushButton_2->setGeometry(120,250,100,30);
  QPushButton_2->setMinimumSize(0,0);
  QPushButton_2->setText(i18n("Cancel"));

  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(50,10,340,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setFont(QFont("helvetica", 20, 50));
  QLabel_1->setText(i18n("KWoodhammer Encryption"));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,50,150,20);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Encryption mode:"));

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(180,50,210,20);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Encryption order:"));

  QButtonGroup_1= new QButtonGroup(this,"NoName");
  QButtonGroup_1->setGeometry(180,80,210,80);
  QButtonGroup_1->setMinimumSize(0,0);

  QRadioButton_7= new QRadioButton(QButtonGroup_1,"NoName");
  QRadioButton_7->setGeometry(10,10,190,20);
  QRadioButton_7->setMinimumSize(0,0);
  KQuickHelp::add(QRadioButton_7,i18n("<red>Trithemius, Johannes (1462-1516)<br><black>A German intellectual who invented a square<br>cryptographic table. It was, as a sequence of<br>shifted Caesars, the base for the first<br>polyalphabetical encryptions.<br><blue>Step by Step<br><black>Use the first letter with the first line<br>of the table, the second one with the<br>second line of the table and so on."));
  QRadioButton_7->setText(i18n("Step-by-step (Trithemius)"));
  QRadioButton_7->setChecked(true);

  QRadioButton_8= new QRadioButton(QButtonGroup_1,"NoName");
  QRadioButton_8->setGeometry(10,30,190,20);
  QRadioButton_8->setMinimumSize(0,0);
  KQuickHelp::add(QRadioButton_8,i18n("<red>Vigenere, Blaise de (1523-1596)<br><black>Dividing key and algorithm, the Frenchman<br>suggested to not commit on the Trithemius algorithm but<br>to change the order of the lines in the table.<br><blue>Password<br><black>This order says to take a keyword for selecting<br>the lines of the table. The line that starts with<br>the corresponding letter is the right one."));
  QRadioButton_8->setText(i18n("Password (Vigenere)"));

  QGroupBox_1= new QGroupBox(this,"NoName");
  QGroupBox_1->setGeometry(10,80,150,80);
  QGroupBox_1->setMinimumSize(0,0);

  QRadioButton_2= new QRadioButton(QGroupBox_1,"NoName");
  QRadioButton_2->setGeometry(10,30,130,20);
  QRadioButton_2->setMinimumSize(0,0);
  QRadioButton_2->setText(i18n("Monoalphabatical"));

  QRadioButton_3= new QRadioButton(QGroupBox_1,"NoName");
  QRadioButton_3->setGeometry(10,50,130,20);
  QRadioButton_3->setMinimumSize(0,0);
  QRadioButton_3->setText(i18n("Polyalphabetical"));
  QRadioButton_3->setChecked(true);

  QRadioButton_1= new QRadioButton(QGroupBox_1,"NoName");
  QRadioButton_1->setGeometry(10,10,130,20);
  QRadioButton_1->setMinimumSize(0,0);
  KQuickHelp::add(QRadioButton_1,i18n("<red>The Caesar algorithm<br><black>Gajus Julius Caesar used a rather simple system to encode<br>his messages. He shifted every letter certain positions<br>to the right, putting the odd ones to the left."));
  QRadioButton_1->setText(i18n("Caesar algorithm"));

  QGroupBox_3= new QGroupBox(this,"NoName");
  QGroupBox_3->setGeometry(10,200,380,40);
  QGroupBox_3->setMinimumSize(0,0);

  QLineEdit_1= new QLineEdit(QGroupBox_3,"NoName");
  QLineEdit_1->setGeometry(10,10,360,20);
  QLineEdit_1->setMinimumSize(0,0);

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,170,100,20);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("The Keyword:"));

  QGroupBox_2= new QGroupBox(this,"NoName");
  QGroupBox_2->setGeometry(10,10,30,30);
  QGroupBox_2->setMinimumSize(0,0);
  QGroupBox_2->setBackgroundPixmap(loader.loadIcon("kwooddecrypt.xpm"));

}
