/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun May 7 16:41:18 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <qpixmap.h>
#include <qfont.h>
#include "info.h"
#include "common.h"

void  info::initDialog(){
  this->resize(350,340);
  this->setMinimumSize(350,300);
  this->setMaximumSize(350,300);
  QGroupBox_1= new QGroupBox(this,"NoName");
  QGroupBox_1->setGeometry(10,10,30,30);
  QGroupBox_1->setMinimumSize(0,0);
  QGroupBox_1->setBackgroundPixmap(QPixmap(iniconhome("kwoodinfo.xpm")));

  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(50,10,290,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setFont(QFont("helvetica", 20, 50));
  QLabel_1->setText(i18n("KWoodhammer Information"));

  QPushButton_1= new QPushButton(this,"NoName");
  QPushButton_1->setGeometry(130,260,100,30);
  QPushButton_1->setMinimumSize(0,0);
  QPushButton_1->setText(i18n("OK"));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,50,330,20);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("KWoodhammer 1.00 (2000-05-04)"));

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,70,330,20);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Copyright (C) 2000 Josef Spillner"));

  QMultiLineEdit_1= new QMultiLineEdit(this,"NoName");
  QMultiLineEdit_1->setGeometry(10,120,330,130);
  QMultiLineEdit_1->setMinimumSize(0,0);
  QMultiLineEdit_1->setText(i18n("The idea to create this cryptographic software had\nbeen influenced by 'Verschlüsselte Geheimnisse'\n(Encrypted Secrets) by Rudolph Kippenhahn where\nhe described most kinds of encryption, from the ages\nof the old Rome to the present.\n\nIn April 2000, I made a contest at my homepage:\nWho cracks the code? During the contest, I made\nKWoodhammer an application which can now\nencrypt and decrypt messages.\n\nFurther information and a step-by-step-instruction\ncan be found at my homepage www.maux.de.\nThe KWoodhammer homepage is\nhttp://kwoodhammer.sourceforge.net."));
  QMultiLineEdit_1->setReadOnly(true);

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,90,330,20);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("dr_maux@users.sourceforge.net"));

}
