/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Tue May 2 20:18:17 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <kiconloader.h>
#include <qfont.h>
#include <qtooltip.h>
#include <qpixmap.h>
#include "kwood.h"
#include "common.h"

void  kwood::initDialog(){
  KIconLoader loader;

  this->resize(450,240);
  this->setMinimumSize(450,260);
  this->setMaximumSize(32767,32767);
  this->setSizeIncrement(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,380,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setFont(QFont("helvetica", 20, 50));
  QLabel_1->setText(i18n("KWoodhammer 1.00"));
  QLabel_1->setMargin(0);

  QMultiLineEdit_1= new QMultiLineEdit(this,"NoName");
  QMultiLineEdit_1->setGeometry(10,90,430,160);
  QMultiLineEdit_1->setMinimumSize(0,0);

  QPushButton_7= new QPushButton(this,"NoName");
  QPushButton_7->setGeometry(320,50,40,30);
  QPushButton_7->setMinimumSize(0,0);
  QToolTip::add(QPushButton_7,i18n("Setup"));
  QPushButton_7->setText(i18n("Button"));
  QPushButton_7->setIsMenuButton(false);
  QPushButton_7->setPixmap(loader.loadIcon("kwoodsetup.xpm"));

  QPushButton_8= new QPushButton(this,"NoName");
  QPushButton_8->setGeometry(170,50,40,30);
  QPushButton_8->setMinimumSize(0,0);
  QToolTip::add(QPushButton_8,i18n("Encryption"));
  QPushButton_8->setText(i18n("Button"));
  QPushButton_8->setPixmap(loader.loadIcon("kwooddecrypt.xpm"));

  QPushButton_9= new QPushButton(this,"NoName");
  QPushButton_9->setGeometry(210,50,40,30);
  QPushButton_9->setMinimumSize(0,0);
  QToolTip::add(QPushButton_9,i18n("Decryption"));
  QPushButton_9->setText(i18n("Button"));
  QPushButton_9->setPixmap(loader.loadIcon("kwoodencrypt.xpm"));

  QPushButton_10= new QPushButton(this,"NoName");
  QPushButton_10->setGeometry(360,50,40,30);
  QPushButton_10->setMinimumSize(0,0);
  QToolTip::add(QPushButton_10,i18n("Information"));
  QPushButton_10->setText(i18n("Button"));
  QPushButton_10->setPixmap(loader.loadIcon("kwoodinfo.xpm"));

  QPushButton_11= new QPushButton(this,"NoName");
  QPushButton_11->setGeometry(400,50,40,30);
  QPushButton_11->setMinimumSize(0,0);
  QToolTip::add(QPushButton_11,i18n("Quit KWoodhammer"));
  QPushButton_11->setText(i18n("Button"));
  QPushButton_11->setPixmap(loader.loadIcon("kwoodexit.xpm"));

  QPushButton_12= new QPushButton(this,"NoName");
  QPushButton_12->setGeometry(10,50,40,30);
  QPushButton_12->setMinimumSize(0,0);
  QToolTip::add(QPushButton_12,i18n("New file"));
  QPushButton_12->setText(i18n("Button"));
  QPushButton_12->setPixmap(loader.loadIcon("kwoodnew.xpm"));

  QPushButton_13= new QPushButton(this,"NoName");
  QPushButton_13->setGeometry(50,50,40,30);
  QPushButton_13->setMinimumSize(0,0);
  QToolTip::add(QPushButton_13,i18n("Load a file"));
  QPushButton_13->setText(i18n("Button"));
  QPushButton_13->setPixmap(loader.loadIcon("kwoodopen.xpm"));

  QPushButton_14= new QPushButton(this,"NoName");
  QPushButton_14->setGeometry(250,50,30,30);
  QPushButton_14->setMinimumSize(0,0);
  QToolTip::add(QPushButton_14,i18n("Key Table"));
  QPushButton_14->setText(i18n("Button"));
  QPushButton_14->setPixmap(loader.loadIcon("kwoodtable.xpm"));

  QPushButton_1= new QPushButton(this,"NoName");
  QPushButton_1->setGeometry(90,50,40,30);
  QPushButton_1->setMinimumSize(0,0);
  QToolTip::add(QPushButton_1,i18n("Save file"));
  QPushButton_1->setText(i18n("Button"));
  QPushButton_1->setPixmap(loader.loadIcon("kwoodsave.xpm"));

}
