/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Tue May 2 19:37:03 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <qfont.h>
#include "progress.h"
#include "common.h"

void  progress::initDialog(){
  this->resize(400,80);
  this->setMinimumSize(400,80);
  this->setMaximumSize(400,80);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,380,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setFont(QFont("helvetica", 20, 50));
  QLabel_1->setText(i18n("KWoodhammer At Work"));

  QProgressBar_1= new QProgressBar(this,"NoName");
  QProgressBar_1->setGeometry(10,50,380,20);
  QProgressBar_1->setMinimumSize(0,0);

}
