/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun May 7 13:38:52 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <kiconloader.h>
#include <qfont.h>
#include <qpixmap.h>
#include "setup.h"
#include "common.h"

void  setup::initDialog(){
  KIconLoader loader;

  this->resize(400,320);
  this->setMinimumSize(400,320);
  this->setMaximumSize(400,320);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(50,10,340,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setFont(QFont("helvetica", 20, 50));
  QLabel_1->setText(i18n("KWoodhammer Setup"));

  QGroupBox_1= new QGroupBox(this,"NoName");
  QGroupBox_1->setGeometry(10,10,30,30);
  QGroupBox_1->setMinimumSize(0,0);
  QGroupBox_1->setBackgroundPixmap(loader.loadIcon("kwoodsetup.xpm"));

  QPushButton_1= new QPushButton(this,"NoName");
  QPushButton_1->setGeometry(10,280,100,30);
  QPushButton_1->setMinimumSize(0,0);
  QPushButton_1->setText(i18n("OK"));

  QPushButton_2= new QPushButton(this,"NoName");
  QPushButton_2->setGeometry(120,280,100,30);
  QPushButton_2->setMinimumSize(0,0);
  QPushButton_2->setText(i18n("Cancel"));

  QRadioButton_5= new QRadioButton(this,"NoName");
  QRadioButton_5->setGeometry(10,210,160,20);
  QRadioButton_5->setMinimumSize(0,0);
  QRadioButton_5->setText(i18n("Use standard statistics"));
  QRadioButton_5->setChecked(true);

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,180,380,20);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Database"));

  QRadioButton_6= new QRadioButton(this,"NoName");
  QRadioButton_6->setGeometry(10,240,160,20);
  QRadioButton_6->setMinimumSize(0,0);
  QRadioButton_6->setText(i18n("Use user statistics"));

  QGroupBox_3= new QGroupBox(this,"NoName");
  QGroupBox_3->setGeometry(10,80,380,90);
  QGroupBox_3->setMinimumSize(0,0);

  QRadioButton_3= new QRadioButton(QGroupBox_3,"NoName");
  QRadioButton_3->setGeometry(10,10,170,20);
  QRadioButton_3->setMinimumSize(0,0);
  QRadioButton_3->setText(i18n("A-Z (26 letters only)"));
  QRadioButton_3->setChecked(true);

  QRadioButton_4= new QRadioButton(QGroupBox_3,"NoName");
  QRadioButton_4->setGeometry(190,10,180,20);
  QRadioButton_4->setMinimumSize(0,0);
  QRadioButton_4->setText(i18n("A-Z, a-z (52 letters)"));

  QCheckBox_2= new QCheckBox(QGroupBox_3,"NoName");
  QCheckBox_2->setGeometry(10,40,360,20);
  QCheckBox_2->setMinimumSize(0,0);
  QCheckBox_2->setText(i18n("Use numbers (using extra chars: 10)"));

  QCheckBox_3= new QCheckBox(QGroupBox_3,"NoName");
  QCheckBox_3->setGeometry(10,60,250,20);
  QCheckBox_3->setMinimumSize(0,0);
  QCheckBox_3->setText(i18n("Use homophony (using extra chars: 0)"));
  QCheckBox_3->setChecked(false);

  QSlider_1= new QSlider(QGroupBox_3,"NoName");
  QSlider_1->setGeometry(270,60,100,20);
  QSlider_1->setMinimumSize(0,0);
  QSlider_1->setEnabled(false);
  QSlider_1->setValue(0);
  QSlider_1->setRange(0,36);
  QSlider_1->setOrientation(QSlider::Horizontal);

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,50,380,20);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Chars encrypted in cleartext and code"));

  QComboBox_1= new QComboBox(this,"NoName");
  QComboBox_1->setGeometry(180,210,140,20);
  QComboBox_1->setMinimumSize(0,0);

  QPushButton_7= new QPushButton(this,"NoName");
  QPushButton_7->setGeometry(180,240,70,20);
  QPushButton_7->setMinimumSize(0,0);
  QPushButton_7->setEnabled(false);
  QPushButton_7->setText(i18n("Add text"));

  QPushButton_8= new QPushButton(this,"NoName");
  QPushButton_8->setGeometry(260,240,60,20);
  QPushButton_8->setMinimumSize(0,0);
  QPushButton_8->setEnabled(false);
  QPushButton_8->setText(i18n("Clear"));

  QPushButton_9= new QPushButton(this,"NoName");
  QPushButton_9->setGeometry(330,240,60,20);
  QPushButton_9->setMinimumSize(0,0);
  QPushButton_9->setEnabled(false);
  QPushButton_9->setText(i18n("Show"));

  QPushButton_10= new QPushButton(this,"NoName");
  QPushButton_10->setGeometry(330,210,60,20);
  QPushButton_10->setMinimumSize(0,0);
  QPushButton_10->setText(i18n("Show"));

  QMultiLineEdit_1= new QMultiLineEdit(this,"NoName");
  QMultiLineEdit_1->setGeometry(360,290,30,20);
  QMultiLineEdit_1->setMinimumSize(0,0);
  QMultiLineEdit_1->hide();

}
